/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GlobalSnackbar: typeof import('./src/components/GlobalSnackbar.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    IpCard: typeof import('./src/components/IpCard.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    PokemonForm: typeof import('./src/components/forms/PokemonForm.vue')['default']
    ProgressCircle: typeof import('./src/components/ProgressCircle.vue')['default']
    RestCountriesCard: typeof import('./src/components/RestCountriesCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
    WeatherForm: typeof import('./src/components/forms/WeatherForm.vue')['default']
  }
}
